/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarymanagement;

import java.awt.Dimension;
import javax.swing.JOptionPane;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.*;
import javax.swing.*;


/**
 *
 * @author Amol
 */
public class Delete extends javax.swing.JFrame {

    Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    /**
     * Creates new form Delete
     */
    public Delete() {
        initComponents();
        Toolkit tk = Toolkit.getDefaultToolkit();
         Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
       /* int w = this.getSize().width;
        int h = this.getSize().height;
        int x = (dim.width-w)/2;
        int y = (dim.height-h)/2;
       */
        
        this.setSize(1366,730);
        //this.setLocation(x,y);
    }
    
     public void close()
    {
        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        get_btn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_book_name = new javax.swing.JTextField();
        txt_author_name = new javax.swing.JTextField();
        txt_price = new javax.swing.JTextField();
        txt_quantity = new javax.swing.JTextField();
        delete_btn = new javax.swing.JButton();
        txt_branch = new javax.swing.JComboBox<>();
        back_btn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Enter Book Id for Deletion :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 220, 160, 30);
        getContentPane().add(txt_id);
        txt_id.setBounds(266, 220, 200, 30);

        get_btn.setText("Get Details");
        get_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                get_btnActionPerformed(evt);
            }
        });
        getContentPane().add(get_btn);
        get_btn.setBounds(365, 263, 100, 30);

        jLabel2.setText("Branch :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 320, 60, 20);

        jLabel3.setText("Book name :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(110, 360, 80, 30);

        jLabel4.setText("Quantity :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(110, 510, 49, 30);

        jLabel5.setText("Author name :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(110, 420, 90, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 255));
        jLabel8.setText("Delete a Book,");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(90, 140, 190, 30);

        jLabel6.setText("Price :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(110, 470, 50, 20);
        getContentPane().add(txt_book_name);
        txt_book_name.setBounds(250, 360, 210, 30);
        getContentPane().add(txt_author_name);
        txt_author_name.setBounds(250, 410, 210, 30);
        getContentPane().add(txt_price);
        txt_price.setBounds(250, 460, 210, 30);
        getContentPane().add(txt_quantity);
        txt_quantity.setBounds(250, 510, 210, 30);

        delete_btn.setText("DELETE");
        delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btnActionPerformed(evt);
            }
        });
        getContentPane().add(delete_btn);
        delete_btn.setBounds(380, 563, 80, 30);

        txt_branch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "computer", "mechanical", "electrical", "electronics" }));
        getContentPane().add(txt_branch);
        txt_branch.setBounds(252, 310, 210, 30);

        back_btn.setText("Back");
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });
        getContentPane().add(back_btn);
        back_btn.setBounds(510, 140, 80, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Amol\\Documents\\NetBeansProjects\\LibraryManagement\\pics\\books.jpg")); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 1370, 730);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void get_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_get_btnActionPerformed
        // TODO add your handling code here:
         try{
             conn=MySqlConnect.ConnectDB();
             String b_id=txt_id.getText();
             
             if(b_id.startsWith("1"))
             {
                 txt_branch.setSelectedIndex(0);
                 pst=conn.prepareStatement("select * from computer where book_id=?");
                 pst.setString(1,txt_id.getText());
                 rs=pst.executeQuery();
                 
                 if(rs.next())
                 {
                     txt_book_name.setText(rs.getString("book_name"));
                     txt_author_name.setText(rs.getString("author_name"));
                     txt_price.setText(rs.getString("price"));
                     txt_quantity.setText(rs.getString("quantity"));      
                 }
             }
             
            if(b_id.startsWith("2"))
             {
                 txt_branch.setSelectedIndex(1);
                 pst=conn.prepareStatement("select * from mechanical where book_id=?");
                 pst.setString(1,txt_id.getText());
                 rs=pst.executeQuery();
                 
                 if(rs.next())
                 {
                     txt_book_name.setText(rs.getString("book_name"));
                     txt_author_name.setText(rs.getString("author_name"));
                     txt_price.setText(rs.getString("price"));
                     txt_quantity.setText(rs.getString("quantity"));      
                 }
             }
            if(b_id.startsWith("3"))
             {
                 txt_branch.setSelectedIndex(2);
                 pst=conn.prepareStatement("select * from electrical where book_id=?");
                 pst.setString(1,txt_id.getText());
                 rs=pst.executeQuery();
                 
                 if(rs.next())
                 {
                     txt_book_name.setText(rs.getString("book_name"));
                     txt_author_name.setText(rs.getString("author_name"));
                     txt_price.setText(rs.getString("price"));
                     txt_quantity.setText(rs.getString("quantity"));      
                 }
             }
            if(b_id.startsWith("4"))
             {
                 txt_branch.setSelectedIndex(3);
                 pst=conn.prepareStatement("select * from electronics where book_id=?");
                 pst.setString(1,txt_id.getText());
                 rs=pst.executeQuery();
                 
                 if(rs.next())
                 {
                     txt_book_name.setText(rs.getString("book_name"));
                     txt_author_name.setText(rs.getString("author_name"));
                     txt_price.setText(rs.getString("price"));
                     txt_quantity.setText(rs.getString("quantity"));      
                 }
             }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_get_btnActionPerformed

    private void delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btnActionPerformed
        // TODO add your handling code here:
        
        try
        {   String str=" ";
            conn=MySqlConnect.ConnectDB();
            
            String b_id=txt_id.getText();
            
            if(b_id.startsWith("1"))
            {
                pst=conn.prepareStatement("delete from computer where book_id=?");
                pst.setString(1, txt_id.getText());
                pst.executeUpdate();
                
                JOptionPane.showMessageDialog(null, "Book is removed from Library");
                
                txt_id.setText(str);
                txt_branch.setSelectedIndex(0);
                txt_book_name.setText(str);
                txt_author_name.setText(str);
                txt_price.setText(str);
                txt_quantity.setText(str);
            }
            else if(b_id.startsWith("2"))
            {
                pst=conn.prepareStatement("delete from mechanical where book_id=?");
                pst.setString(1, txt_id.getText());
                pst.executeUpdate();
                
                JOptionPane.showMessageDialog(null, "Book is removed from Library");
                
                txt_id.setText(str);
                txt_branch.setSelectedIndex(0);
                txt_book_name.setText(str);
                txt_author_name.setText(str);
                txt_price.setText(str);
                txt_quantity.setText(str);
            }
            else if(b_id.startsWith("3"))
            {
                pst=conn.prepareStatement("delete from electrical where book_id=?");
                pst.setString(1, txt_id.getText());
                pst.executeUpdate();
                
                JOptionPane.showMessageDialog(null, "Book is removed from Library");
                
                txt_id.setText(str);
                txt_branch.setSelectedIndex(0);
                txt_book_name.setText(str);
                txt_author_name.setText(str);
                txt_price.setText(str);
                txt_quantity.setText(str);
            }
            else if(b_id.startsWith("4"))
            {
                pst=conn.prepareStatement("delete from electronics where book_id=?");
                pst.setString(1, txt_id.getText());
                pst.executeUpdate();
                
                JOptionPane.showMessageDialog(null, "Book is removed from Library");
                
                txt_id.setText(str);
                txt_branch.setSelectedIndex(0);
                txt_book_name.setText(str);
                txt_author_name.setText(str);
                txt_price.setText(str);
                txt_quantity.setText(str);
            }
            else
            {
                 JOptionPane.showMessageDialog(null, "Invalid Book Id entered !!","Access Denied",JOptionPane.ERROR_MESSAGE);
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_delete_btnActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        // TODO add your handling code here:
        close();
        Lib_Book_Details lbd=new Lib_Book_Details();
        lbd.setVisible(true);
        
    }//GEN-LAST:event_back_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Delete().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_btn;
    private javax.swing.JButton delete_btn;
    private javax.swing.JButton get_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txt_author_name;
    private javax.swing.JTextField txt_book_name;
    private javax.swing.JComboBox<String> txt_branch;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_price;
    private javax.swing.JTextField txt_quantity;
    // End of variables declaration//GEN-END:variables
}
