/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarymanagement;

import java.awt.Dimension;
import javax.swing.JOptionPane;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.*;
import javax.swing.*;

/**
 *
 * @author Amol
 */
public class Insert extends javax.swing.JFrame {

    Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    /**
     * Creates new form Insert
     */
    public Insert() {
        initComponents();
        Toolkit tk = Toolkit.getDefaultToolkit();
         Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
       /* int w = this.getSize().width;
        int h = this.getSize().height;
        int x = (dim.width-w)/2;
        int y = (dim.height-h)/2;
       */
        
        this.setSize(1366,730);
        //this.setLocation(x,y);
    }
    
      public void close()
    {
        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Quantity = new javax.swing.JLabel();
        txt_branch = new javax.swing.JComboBox<>();
        txt_book_name = new javax.swing.JTextField();
        txt_author_name = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_price = new javax.swing.JTextField();
        txt_quantity = new javax.swing.JTextField();
        insert_btn = new javax.swing.JButton();
        back_btn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Branch :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 240, 60, 20);

        jLabel2.setText("Book Name :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 300, 80, 30);

        jLabel3.setText("Author Name :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(110, 360, 90, 30);

        jLabel4.setText("Price :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(110, 430, 50, 20);

        Quantity.setText("Quantity :");
        getContentPane().add(Quantity);
        Quantity.setBounds(110, 490, 80, 20);

        txt_branch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "computer", "mechanical", "electrical", "electronics" }));
        txt_branch.setToolTipText("");
        getContentPane().add(txt_branch);
        txt_branch.setBounds(240, 240, 220, 30);
        getContentPane().add(txt_book_name);
        txt_book_name.setBounds(240, 300, 220, 30);

        txt_author_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_author_nameActionPerformed(evt);
            }
        });
        getContentPane().add(txt_author_name);
        txt_author_name.setBounds(240, 360, 220, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 255));
        jLabel6.setText("Insert a Book,");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(100, 150, 190, 30);
        getContentPane().add(txt_price);
        txt_price.setBounds(240, 420, 220, 30);
        getContentPane().add(txt_quantity);
        txt_quantity.setBounds(240, 480, 220, 30);

        insert_btn.setText("INSERT");
        insert_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insert_btnActionPerformed(evt);
            }
        });
        getContentPane().add(insert_btn);
        insert_btn.setBounds(380, 540, 80, 30);

        back_btn.setText("Back");
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });
        getContentPane().add(back_btn);
        back_btn.setBounds(490, 150, 90, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Amol\\Documents\\NetBeansProjects\\LibraryManagement\\pics\\books.jpg")); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 1370, 730);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insert_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insert_btnActionPerformed
        // TODO add your handling code here:
        try
        { String str=" ";
            conn=MySqlConnect.ConnectDB();
            
            String br=txt_branch.getSelectedItem().toString();
            
            if(br.equalsIgnoreCase("computer"))
            {
                pst=conn.prepareStatement("insert into computer(book_name,author_name,price,quantity) values('"+txt_book_name.getText()+"','"+txt_author_name.getText()+"',"+txt_price.getText()+","+txt_quantity.getText()+")");
                pst.executeUpdate();
                
                pst=conn.prepareStatement("select * from computer where book_name=? and author_name=?");
                pst.setString(1,txt_book_name.getText());
                pst.setString(2,txt_author_name.getText());
                rs=pst.executeQuery();
                
                if(rs.next())
                {
                    JOptionPane.showMessageDialog(null,"Book ID : "+rs.getString(1)+" is inserted in Computer branch");
                    txt_branch.setSelectedIndex(0);
                    txt_book_name.setText(str);
                    txt_author_name.setText(str);
                    txt_price.setText(str);
                    txt_quantity.setText(str);
                }
            }
            
             if(br.equalsIgnoreCase("electrical"))
            {
                 pst=conn.prepareStatement("insert into electrical(book_name,author_name,price,quantity) values('"+txt_book_name.getText()+"','"+txt_author_name.getText()+"',"+txt_price.getText()+","+txt_quantity.getText()+")");
                pst.executeUpdate();
                
                pst=conn.prepareStatement("select * from electrical where book_name=? and author_name=?");
                pst.setString(1,txt_book_name.getText());
                pst.setString(2,txt_author_name.getText());
                rs=pst.executeQuery();
                
                if(rs.next())
                {
                    JOptionPane.showMessageDialog(null,"Book ID : "+rs.getString(1)+" is inserted in Electrical branch");
                    txt_branch.setSelectedIndex(0);
                    txt_book_name.setText(str);
                    txt_author_name.setText(str);
                    txt_price.setText(str);
                    txt_quantity.setText(str);
                }
            }
             
             if(br.equalsIgnoreCase("electronics"))
            {
                 pst=conn.prepareStatement("insert into electronics(book_name,author_name,price,quantity) values('"+txt_book_name.getText()+"','"+txt_author_name.getText()+"',"+txt_price.getText()+","+txt_quantity.getText()+")");
                pst.executeUpdate();
                
                pst=conn.prepareStatement("select * from electronics where book_name=? and author_name=?");
                pst.setString(1,txt_book_name.getText());
                pst.setString(2,txt_author_name.getText());
                rs=pst.executeQuery();
                
                if(rs.next())
                {
                    JOptionPane.showMessageDialog(null,"Book ID : "+rs.getString(1)+" is inserted in Electronics branch");
                    txt_branch.setSelectedIndex(0);
                    txt_book_name.setText(str);
                    txt_author_name.setText(str);
                    txt_price.setText(str);
                    txt_quantity.setText(str);
                }
            }
             
             if(br.equalsIgnoreCase("mechanical"))
            {
                 pst=conn.prepareStatement("insert into mechanical(book_name,author_name,price,quantity) values('"+txt_book_name.getText()+"','"+txt_author_name.getText()+"',"+txt_price.getText()+","+txt_quantity.getText()+")");
                pst.executeUpdate();
                
                pst=conn.prepareStatement("select * from mechanical where book_name=? and author_name=?");
                pst.setString(1,txt_book_name.getText());
                pst.setString(2,txt_author_name.getText());
                rs=pst.executeQuery();
                
                if(rs.next())
                {
                    JOptionPane.showMessageDialog(null,"Book ID : "+rs.getString(1)+" is inserted in Mechanical branch");
                    txt_branch.setSelectedIndex(0);
                    txt_book_name.setText(str);
                    txt_author_name.setText(str);
                    txt_price.setText(str);
                    txt_quantity.setText(str);
                }
            } 
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_insert_btnActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        // TODO add your handling code here:
        close();
        Lib_Book_Details lbd=new Lib_Book_Details();
        lbd.setVisible(true);
        
    }//GEN-LAST:event_back_btnActionPerformed

    private void txt_author_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_author_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_author_nameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Insert().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Quantity;
    private javax.swing.JButton back_btn;
    private javax.swing.JButton insert_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txt_author_name;
    private javax.swing.JTextField txt_book_name;
    private javax.swing.JComboBox<String> txt_branch;
    private javax.swing.JTextField txt_price;
    private javax.swing.JTextField txt_quantity;
    // End of variables declaration//GEN-END:variables
}
