/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarymanagement;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.*;
import javax.swing.*;

/**
 *
 * @author Amol
 */
public class Update extends javax.swing.JFrame {

    Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    /**
     * Creates new form Update
     */
    public Update() {
        initComponents();
        Toolkit tk = Toolkit.getDefaultToolkit();
         Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
       /* int w = this.getSize().width;
        int h = this.getSize().height;
        int x = (dim.width-w)/2;
        int y = (dim.height-h)/2;
       */
        
        this.setSize(1366,730);
        //this.setLocation(x,y);
    }
    
     public void close()
    {
        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_id = new javax.swing.JTextField();
        get_btn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_author_name = new javax.swing.JTextField();
        txt_book_name = new javax.swing.JTextField();
        txt_price = new javax.swing.JTextField();
        txt_quantity = new javax.swing.JTextField();
        update_btn = new javax.swing.JButton();
        txt_branch = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        back_btn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        get_btn.setText("Get Details");
        get_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                get_btnActionPerformed(evt);
            }
        });

        jLabel2.setText("Branch :");

        jLabel3.setText("Book_name :");

        jLabel4.setText("Author_name :");

        jLabel5.setText("Price :");

        jLabel6.setText("Quantity :");

        update_btn.setText("Update");
        update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_btnActionPerformed(evt);
            }
        });

        txt_branch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "computer", "mechanical", "electrical", "electronics" }));

        jLabel7.setText("Enter Book Id for Updation :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(50, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_book_name)
                            .addComponent(txt_author_name)
                            .addComponent(txt_price)
                            .addComponent(txt_quantity)
                            .addComponent(txt_branch, 0, 166, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(txt_id))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(update_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(get_btn)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(get_btn)
                    .addComponent(jLabel7))
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_branch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_book_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4))
                    .addComponent(txt_author_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(update_btn)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(80, 170, 440, 430);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setText("Update a Book,");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 134, 190, 30);

        back_btn.setText("Back");
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });
        getContentPane().add(back_btn);
        back_btn.setBounds(530, 140, 55, 23);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Amol\\Documents\\NetBeansProjects\\LibraryManagement\\pics\\books.jpg")); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 1370, 730);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void get_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_get_btnActionPerformed
        // TODO add your handling code here:
        
        try{
             conn=MySqlConnect.ConnectDB();
             String b_id=txt_id.getText();
             
             if(b_id.startsWith("1"))
             {
                 txt_branch.setSelectedIndex(0);
                 pst=conn.prepareStatement("select * from computer where book_id=?");
                 pst.setString(1,txt_id.getText());
                 rs=pst.executeQuery();
                 
                 if(rs.next())
                 {
                     txt_book_name.setText(rs.getString("book_name"));
                     txt_author_name.setText(rs.getString("author_name"));
                     txt_price.setText(rs.getString("price"));
                     txt_quantity.setText(rs.getString("quantity"));      
                 }
             }
             
            if(b_id.startsWith("2"))
             {
                 txt_branch.setSelectedIndex(1);
                 pst=conn.prepareStatement("select * from mechanical where book_id=?");
                 pst.setString(1,txt_id.getText());
                 rs=pst.executeQuery();
                 
                 if(rs.next())
                 {
                     txt_book_name.setText(rs.getString("book_name"));
                     txt_author_name.setText(rs.getString("author_name"));
                     txt_price.setText(rs.getString("price"));
                     txt_quantity.setText(rs.getString("quantity"));      
                 }
             }
            if(b_id.startsWith("3"))
             {
                 txt_branch.setSelectedIndex(2);
                 pst=conn.prepareStatement("select * from electrical where book_id=?");
                 pst.setString(1,txt_id.getText());
                 rs=pst.executeQuery();
                 
                 if(rs.next())
                 {
                     txt_book_name.setText(rs.getString("book_name"));
                     txt_author_name.setText(rs.getString("author_name"));
                     txt_price.setText(rs.getString("price"));
                     txt_quantity.setText(rs.getString("quantity"));      
                 }
             }
            if(b_id.startsWith("4"))
             {
                 txt_branch.setSelectedIndex(3);
                 pst=conn.prepareStatement("select * from electronics where book_id=?");
                 pst.setString(1,txt_id.getText());
                 rs=pst.executeQuery();
                 
                 if(rs.next())
                 {
                     txt_book_name.setText(rs.getString("book_name"));
                     txt_author_name.setText(rs.getString("author_name"));
                     txt_price.setText(rs.getString("price"));
                     txt_quantity.setText(rs.getString("quantity"));      
                 }
             }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_get_btnActionPerformed

    private void update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_btnActionPerformed
        // TODO add your handling code here:
        try{ String str=" ";
             conn=MySqlConnect.ConnectDB();
             String b_id=txt_id.getText();
             
             if(b_id.startsWith("1"))
             {
                pst=conn.prepareStatement("update computer set book_name=?,author_name=?,price=?,quantity=? where book_id=?");
                pst.setString(1, txt_book_name.getText());
                pst.setString(2, txt_author_name.getText());
                pst.setString(3, txt_price.getText());
                pst.setString(4, txt_quantity.getText());
                pst.setString(5, txt_id.getText());
                int i=pst.executeUpdate();
                
                if(i>0)
                {
                    JOptionPane.showMessageDialog(null, "Book details updated successfully");
                    txt_branch.setSelectedIndex(0);
                    txt_book_name.setText(str);
                    txt_author_name.setText(str);
                    txt_price.setText(str);
                    txt_quantity.setText(str);
                    txt_id.setText(str);
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Wrong book id entered");

                }
                
             }
             else if(b_id.startsWith("2"))
             {
                pst=conn.prepareStatement("update mechanical set book_name=?,author_name=?,price=?,quantity=? where book_id=?");
                pst.setString(1, txt_book_name.getText());
                pst.setString(2, txt_author_name.getText());
                pst.setString(3, txt_price.getText());
                pst.setString(4, txt_quantity.getText());
                pst.setString(5, txt_id.getText());
                int i=pst.executeUpdate();
                
                if(i>0)
                {
                    JOptionPane.showMessageDialog(null, "Book details updated successfully");
                    txt_branch.setSelectedIndex(0);
                    txt_book_name.setText(str);
                    txt_author_name.setText(str);
                    txt_price.setText(str);
                    txt_quantity.setText(str);
                    txt_id.setText(str);
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Wrong book id entered");

                }
                
             }
             else if(b_id.startsWith("3"))
             {
                pst=conn.prepareStatement("update electrical set book_name=?,author_name=?,price=?,quantity=? where book_id=?");
                pst.setString(1, txt_book_name.getText());
                pst.setString(2, txt_author_name.getText());
                pst.setString(3, txt_price.getText());
                pst.setString(4, txt_quantity.getText());
                pst.setString(5, txt_id.getText());
                int i=pst.executeUpdate();
                
                if(i>0)
                {
                    JOptionPane.showMessageDialog(null, "Book details updated successfully");
                    txt_branch.setSelectedIndex(0);
                    txt_book_name.setText(str);
                    txt_author_name.setText(str);
                    txt_price.setText(str);
                    txt_quantity.setText(str);
                    txt_id.setText(str);
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Wrong book id entered");

                }
                
             }
             else if(b_id.startsWith("4"))
             {
                pst=conn.prepareStatement("update electronics set book_name=?,author_name=?,price=?,quantity=? where book_id=?");
                pst.setString(1, txt_book_name.getText());
                pst.setString(2, txt_author_name.getText());
                pst.setString(3, txt_price.getText());
                pst.setString(4, txt_quantity.getText());
                pst.setString(5, txt_id.getText());
                int i=pst.executeUpdate();
                
                if(i>0)
                {
                    JOptionPane.showMessageDialog(null, "Book details updated successfully");
                    txt_branch.setSelectedIndex(0);
                    txt_book_name.setText(str);
                    txt_author_name.setText(str);
                    txt_price.setText(str);
                    txt_quantity.setText(str);
                    txt_id.setText(str);
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Wrong book id entered");

                }
                
             }
             else
             {
                 JOptionPane.showMessageDialog(null, "Invalid book id entered");

             }
             
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_update_btnActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        // TODO add your handling code here:
        close();
        Lib_Book_Details lbd=new Lib_Book_Details();
        lbd.setVisible(true);
    }//GEN-LAST:event_back_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Update().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_btn;
    private javax.swing.JButton get_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_author_name;
    private javax.swing.JTextField txt_book_name;
    private javax.swing.JComboBox<String> txt_branch;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_price;
    private javax.swing.JTextField txt_quantity;
    private javax.swing.JButton update_btn;
    // End of variables declaration//GEN-END:variables
}
